[package]
name = "cloudscoop"
version = "0.1.0"
authors = ["Josh Leverette <coder543@gmail.com>"]
description = "Compiler toolchain written in Rust, maybe someday"
license = "GPL-3.0"

[dependencies]
